import time
age = eval(input("HOW OLD ARE YOU?"))
if age < 5:
    print("UH OH! YOU NEED TO BE 6 OR OLDER TO PLAY.")
    quit()
print("WE RECCOMEND PLAYING THE RUNAWAY 2 AND 1.")
your_name = input("WHAT IS YOUR NAME?")
time.sleep(1)
print("DO YOU WANT TO GO AND CHECK IT OUT RIGHT NOW?")
yee = input("EITHER ENTER IN 'Yes' OR 'No'. : ")
if yee.lower() == 'yes':
    print("OKAY! NOW IS YOUR TIME TO CHECK IT OUT.")
    quit()
print("OKAY. SORRY FOR THE INCONVENIENCE, BUT YOU HAVE TO FILL OUT THIS FORM.")
fav_weapon = input("WHAT'S YOUR FAVORITE CLOSE-RANGED WEAPON?")
fav_far_weapon = input("WHAT'S YOUR FAVORITE FAR-RANGED WEAPON?")
teleport_object = input("WHAT'S YOUR FAVORITE FAST-TRAVEL ITEM?")
print("DO YOU HAVE A CODE?")
YEE = input("EITHER ENTER IN 'Yes' OR 'No'. : ")
if YEE.lower() =='yes':
    print("OKAY THAN, WHAT'S YOUR CODE? (THE CODE HAS TO BE PRESICE.)")
    code = input("ENTER YOUR CODE: ")
if code == 'a;sd|g($$':
    print("BLOOP. ZZZ. FCRATCHH.")
    time.sleep(1)
    print("CODE VAILD.")
    coins = 20
    time.sleep(1)
    print(" _________________       _______________         _____________")
    print("         |               |_____________|         ____________| ")
    print("         | HE            |              |UNAWAY  ____________| ")
    input("PRESS ENTER TO START!")
    print("[AADFOUTAMIE]: PARADOX IS A LOT OF HELP.")
    time.sleep(1)
    print("[AADFOUTAMIE]: HEY... WHAT'S THIS? ANOTHER LAND?")
    time.sleep(1)
    print("[",your_name,"]: IT DOSEN'T SHOW THIS ON THE",teleport_object,"...")
    time.sleep(1)
    print("YOU ENTER THE LAND. A SIGN SAIS: '∑´´çøµ´ †ø †˙´ ´´´´†®ˆˆå¬ ¬å˜˜!'")
    time.sleep(1)
    print("YOU SEE A VLLAGE. YOU ENTER IT.")
    time.sleep(1)
    print("[RANDOM VILLAGER]: ˙´´¬ø †˙´´´´")
    time.sleep(1)
    print("[AADFOUTAMIE]: WE SHOULD BUY A TRANSLATOR FROM THE SHOPPE.")
    time.sleep(1)
    print("YOU ENTER THE SHOPPE.")
    time.sleep(1)
    print("[ACCOUNTANT]: DOO YER UNDERSTANDE ME??")
    time.sleep(1)
    print("[AADFOUTAMIE]: OH YES I DO.")
    time.sleep(1)
    print("[ACCOUNTANT]: I CAN SEE THAT YOU HAVE ENOUGH MONEY.")
    time.sleep(1)
    print("YOU BUY THE TRANSLATOR.")
    time.sleep(1)
if code == 'KSks(*98':
    print("BLOOP. ZZZ. FCRATCHH.")
    time.sleep(1)
    print("CODE VAILD.")
    coins = 0
    time.sleep(1)
    print(" _________________       _______________         _____________")
    print("         |               |_____________|         ____________| ")
    print("         | HE            |              |UNAWAY  ____________| ")
    input("PRESS ENTER TO START!")
    print("[AADFOUTAMIE]: PARADOX IS A LOT OF HELP.")
    time.sleep(1)
    print("[AADFOUTAMIE]: HEY... WHAT'S THIS? ANOTHER LAND?")
    time.sleep(1)
    print("[", your_name, "]: IT DOSEN'T SHOW THIS ON THE", teleport_object, "...")
    time.sleep(1)
    print("YOU ENTER THE LAND. A SIGN SAIS: '∑´´çøµ´ †ø †˙´ ´´´´†®ˆˆå¬ ¬å˜˜!'")
    time.sleep(1)
    print("YOU SEE A VLLAGE. YOU ENTER IT.")
    time.sleep(1)
    print("[RANDOM VILLAGER]: ˙´´¬ø †˙´´´´")
    time.sleep(1)
    print("[AADFOUTAMIE]: WE SHOULD BUY A TRANSLATOR FROM THE SHOPPE.")
    time.sleep(1)
    print("YOU ENTER THE SHOPPE.")
    time.sleep(1)
    print("[ACCOUNTANT]: DOO YER UNDERSTANDE ME??")
    time.sleep(1)
    print("[AADFOUTAMIE]: OH YES I DO.")
    time.sleep(1)
    print("[ACCOUNTANT]: DO YOU HAVE ENOUGH MONEY?")
    time.sleep(1)
    FARYYT = input("YES OR NO?")
    if FARYYT.lower == 'yes':
        print("[ACCOUNTANT]: HUMM..")
        time.sleep(1)
        print("THE ACCOUNTANT IS COUNTING FAKE MONEY.")
        time.sleep(1)
        print("YOU EXIT THE SHOPP-")
        time.sleep(1)
        print("[ACCOUNTANT]: HEY! THIS IS FAKE MONEY! YOU LIAR!!")
        time.sleep(1)
        print(your_name,"WAS SLAIN BY ACCOUNTANT.")
        quit()
    print("[ACCOUNTANT]: OKAY, I CAN OFFER YOU A JOB.")
    time.sleep(1)
    print("YOU ACCEPT THE JOB.")
    time.sleep(1)
    print("YOU HAVE TO CHOP WOOD.")
    time.sleep(1)
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'left':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name,"WAS SLAIN BY TREE")
        quit()
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'down':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name, "WAS SLAIN BY TREE")
        quit()
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'right':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name, "WAS SLAIN BY TREE")
        quit()
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'up':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name, "WAS SLAIN BY TREE")
        quit()
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'left':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name, "WAS SLAIN BY TREE")
        quit()
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'left':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name, "WAS SLAIN BY TREE")
        quit()
    print("DO YOU CHOP UP, DOWN, LEFT OR RIGHT?")
    time.sleep(1)
    LRDW = input("ENTER HERE: ")
    if LRDW.lower != 'right':
        print("YOU GOT SPIKED BY A SPIKE ON THE TREE!")
        time.sleep(1)
        print(your_name, "WAS SLAIN BY TREE")
        quit()
    print("YOU GET PAID 20$.")
    time.sleep(1)
    print("YOU BUY THE TRANSLATOR.")
    time.sleep(1)
print("YOU USE THE TRANSLATOR AND READ THE SIGNS.")
time.sleep(1)
bl = input("DO YOU GO INTO THE WOODS, THE CASTLE, OR THE POND?")
if bl.lower == 'woods':
    print("YOU ENTER THE WOODS. BUT YOU GET LOST!")
    time.sleep(1)
    print("YOU HEAR GRUMBLING. IT'S A BEAR!!!")
    time.sleep(1)
    print(your_name,"WAS SLAIN BY BEAR.")
    quit()
if bl.lower == 'pond':
    print("YOU GO CLOSE TO THE POND.")
    time.sleep(1)
    print("YOU SEE BUBBLES ON THE SURFACE OF THE WATER.")
    time.sleep(1)
    print("AN OCTOPUS PULLS YOU INTO THE WATER AND DROWNS YOU!")
    time.sleep(1)
    print(your_name,"WAS SLAIN BY AN OCTOPUS.")
    quit()
if bl.lower == 'castle':
    print("YOU ENTER THE CASTLE. YOU ENTER THE THRONE ROOM, AND YOU SEE PARADOX SITTING ON THE THRONE.")
    time.sleep(1)
    print("[PARADOX]: HI!")
    time.sleep(1)
    LOBOI = input("WHAT DO YOU SAY TO PARADOX? ")
    time.sleep(1)
    print("[",your_name,"]:",LOBOI)
    time.sleep(1)
    print("[PARADOX]: OH WELL, FORGET ABOUT THAT, I CAN GIVE YOU A FREE RIDE INTO YOUR VILLAGE.")
    time.sleep(1)
    print("YOU RIDA")