import time
age = eval(input("HOW OLD ARE YOU?"))
if age < 5:
    print("UH OH! YOU NEED TO BE 6 OR OLDER TO PLAY.")
    quit()
print("WE RECCOMEND PLAYING THE RUNAWAY 1.")
your_name = input("WHAT IS YOUR NAME?")
time.sleep(1)
print("DO YOU WANT TO GO AND CHECK IT OUT RIGHT NOW?")
yee = input("EITHER ENTER IN 'Yes' OR 'No'. : ")
level = 0
if yee.lower() == 'yes':
    print("OKAY! NOW IS YOUR TIME TO CHECK IT OUT.")
    quit()
print("OKAY. SORRY FOR THE INCONVENIENCE, BUT YOU HAVE TO FILL OUT THIS FORM.")
fav_weapon = input("WHAT'S YOUR FAVORITE CLOSE-RANGED WEAPON?")
fav_far_weapon = input("WHAT'S YOUR FAVORITE FAR-RANGED WEAPON?")
teleport_object = input("WHAT'S YOUR FAVORITE FAST-TRAVEL ITEM?")
print("DO YOU HAVE A CODE?")
YEE = input("EITHER ENTER IN 'Yes' OR 'No'. : ")
if YEE.lower() == 'yes':
    print("OKAY THAN, WHAT'S YOUR CODE? (THE CODE HAS TO BE PRESICE.)")
    code = input("ENTER YOUR CODE: ")
    if code == 'gGhH1!2@':
        print("ANALYSING...")
        time.sleep(3)
        print("CODE VALID.")
        time.sleep(1)
        print(" _________________       _______________         _____________")
        print("         |               |_____________|         ____________| ")
        print("         | HE            |              |UNAWAY  |____________ ")
        level = 3
        input("PRESS ENTER TO START!")
        print("[AADFOUTAMIE]: TO GET TO YOUR HOME, WE NEED TO PASS THE ACID LAND.")
        time.sleep(1)
        print("[AADFOUTAMIE]: IT'S VERY DANGEROUS. YOU WILL NEED TO PASS THROUGH BY JUMPING ON TREES AND ROCKS.")
        time.sleep(1)
        print("[", your_name, "]: HAHA! WHY ARE YOU SO DUMB? I HAVE A FAST-TRAVEL", teleport_object, "!")
        time.sleep(1)
        print("[AADFOUTAMIE]: OH YEAH!")
        time.sleep(1)
        print("[AADFOUTAMIE]: UH OH! YOUR VILLAGE IS BLOCKED ON THE", teleport_object, "!")
        time.sleep(1)
        print("[AADFOUTAMIE]:  WE CAN'T INSTANTLY FAST-TRAVEL THERE!")
        time.sleep(1)
        print("[", your_name, "]: OH NOOOOOOOOOO!!!")
        time.sleep(1)
        print("[AADFOUTAMIE]: SO WE CAN ONLY FAST-TRAVEL INTO OF THE VILLAGE.")
        time.sleep(1)
        print("BWAZZAK!")
    if code == 'q1w2e3r4':
        print("ANALYSING...")
        time.sleep(3)
        print("CODE VALID.")
        time.sleep(1)
        print(" _________________       _______________         _____________")
        print("         |               |_____________|         ____________| ")
        print("         | HE            |              |UNAWAY  |____________ ")
        level = 2
        input("PRESS ENTER TO START!")
        time.sleep(1)
        print("[AADFOUTAMIE]: TO GET TO YOUR HOME, WE NEED TO PASS THE ACID LAND.")
        time.sleep(1)
        print("[AADFOUTAMIE]: IT'S VERY DANGEROUS. YOU WILL NEED TO PASS THROUGH BY JUMPING ON TREES AND ROCKS.")
        time.sleep(1)
        print("BOOT!")
        time.sleep(1)
        print("STEP!")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("[AADFOUTAMIE]: OKAY! NOW WE ARE AT THE BORDER OF THE ACID LAND!")
        time.sleep(1)
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT != 'L':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT1 = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT1 != 'R':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT != 'L':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT != 'L':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT != 'R':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT != 'L':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("DO YOU GO TO THE LEFT OR THE RIGHT?")
        LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
        if LEFT_OR_RIGHT != 'L':
            print("YOU FALL INTO A PIT. THE END.")
            quit()
        print("[AADFOUMATIE]: PHOOO BOOOY! WE FINALLY MADE IT!")
        time.sleep(1)
        print("YOU SEE A CHEST.")
        time.sleep(1)
        print("AADFOUMATIE OPENS IT.")
        time.sleep(1)
        print("YOU GOT A", teleport_object, "!!!")
        print("LEVEL UP!!! 2 -> 3")
        level = 3
if YEE.lower() == 'no':
    print(" _________________       _______________         _____________")
    print("         |               |_____________|         ____________| ")
    print("         | HE            |              |UNAWAY  |____________ ")
    level = 2
    input("PRESS ENTER TO SEE THE RECAP!")
    time.sleep(1)
    print("RECAP:")
    time.sleep(1)
    print("LAST TIME, YOU GOT CAPTURED BY THE ZLASKOIY TRIBE AND YOU MET A ROBOT CALLED AADFOUTAMIE.")
    time.sleep(1)
    print("YOU MET 2 PEOPLE NAMED PARADOX AND OCTOPUS. YOU ESCAPED AND RAN AWAY, TO GET BACK HOME.")
    time.sleep(1)
    print("SINCE YOU DIDN'T PLAY THE RUNAWAY 1, WE CAN ONLY START YOU AT THE 50% ENDING.")
    time.sleep(1)
    print("YOU ARE IN LEVEL 2, YOU HAVE A", fav_weapon, "and a", fav_far_weapon, ".")
    time.sleep(1)
    input("PRESS ENTER TO START")
    print("[AADFOUTAMIE]: TO GET TO YOUR HOME, WE NEED TO PASS THE ACID LAND.")
    time.sleep(1)
    print("[AADFOUTAMIE]: IT'S VERY DANGEROUS. YOU WILL NEED TO PASS THROUGH BY JUMPING ON TREES AND ROCKS.")
    time.sleep(1)
    print("BOOT!")
    time.sleep(1)
    print("STEP!")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("[AADFOUTAMIE]: OKAY! NOW WE ARE AT THE BORDER OF THE ACID LAND!")
    time.sleep(1)
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT != 'L':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT1 = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT1 != 'R':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT != 'L':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT != 'L':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT != 'R':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT != 'L':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("DO YOU GO TO THE LEFT OR THE RIGHT?")
    LEFT_OR_RIGHT = input("TYPE IN 'L' FOR LEFT AND 'R' FOR RIGHT.")
    if LEFT_OR_RIGHT != 'L':
        print("YOU FALL INTO A PIT. THE END.")
        quit()
    print("[AADFOUMATIE]: PHOOO BOOOY! WE FINALLY MADE IT!")
    time.sleep(1)
    print("YOU SEE A CHEST.")
    time.sleep(1)
    print("AADFOUMATIE OPENS IT.")
    time.sleep(1)
    print("YOU GOT A", teleport_object, "!!!")
    time.sleep(1)
time.sleep(1)
print("YOU SEE A CHEST.")
print("YOU OPEN IT.")
print("INSIDE THERE IS A SHEET OF PAPAER THAT SAIS: CHOP CHOP LDRULLR.")
print("UH OH! THERE IS AN ACID POOL IN FRONT OF YOU!")
time.sleep(1)
print("DO YOU STAND AT THE SAME SPOT OR GO AROUND?")
time.sleep(1)
around = input("STAND FOR STAND AT THE SAME SPOT AND AROUND FOR GOING AROUND.")
time.sleep(1)
if around.lower() == 'stand':
    print("ZZZZAAAPPP!!!")
    time.sleep(1)
    print("[", your_name, "]: AAH!")
    time.sleep(1)
    print("[AADFOUMATIE]: AAAAAAAAAAHHHHHHHHHHHHHH!!!!")
    time.sleep(1)
    print("YOU SEE A BIG § SYMBOL IN FRONT OF YOU.")
    time.sleep(1)
    print("THE § SYBOL FADES AWAY AND BECAOMES PARADOX!")
    time.sleep(1)
    print("[PARADOX]: LOOKS LIKE YOU GUYS WERE HAVING SOME TROUBLE HERE.")
    time.sleep(1)
    lala = input("WHAT ARE YOU GOING TO SAY TO PARADOX? :")
    time.sleep(1)
    print("[", your_name, "]:", lala)
    time.sleep(1)
    print("[PARADOX]: DON'T YOU MEAN I SHOULD BUILD A BRIDGE FOR YOU?")
    time.sleep(1)
    print("PARADOX BUILDS A BRIDGE FOR YOU.")
    time.sleep(1)
    print("[PARADOX]: UDDUUD.")
    time.sleep(1)
    print("PARADOX VANISHES.")
    time.sleep(1)
    print("[AADFOUMATIE]: THAT MIGHT BE A CODE.")
    time.sleep(1)
    print("A BIRD SWEEPS UNDER YOU AND CARRIES YOU.")
    time.sleep(1)
    print("YOU CAN CONTROL THE BIRD. 'U' FOR UP AND 'D' FOR DOWN.")
    SYCHOMMIE = input("DO YOU GO UP OR DOWN?")
    if SYCHOMMIE != 'U':
        print("THE BIRD CRASHES INTO A TREE. YOU FALL DOWN. THE END.")
        quit()
    print("YOU CAN CONTROL THE BIRD. 'U' FOR UP AND 'D' FOR DOWN.")
    SYCHOMMIE = input("DO YOU GO UP OR DOWN?")
    if SYCHOMMIE != 'D':
        print("THE BIRD CRASHES INTO A TREE. YOU FALL DOWN. THE END.")
        quit()
    print("YOU CAN CONTROL THE BIRD. 'U' FOR UP AND 'D' FOR DOWN.")
    SYCHOMMIE = input("DO YOU GO UP OR DOWN?")
    if SYCHOMMIE != 'D':
        print("THE BIRD CRASHES INTO A TREE. YOU FALL DOWN. THE END.")
        quit()
    print("YOU CAN CONTROL THE BIRD. 'U' FOR UP AND 'D' FOR DOWN.")
    SYCHOMMIE = input("DO YOU GO UP OR DOWN?")
    if SYCHOMMIE != 'U':
        print("THE BIRD CRASHES INTO A TREE. YOU FALL DOWN. THE END.")
        quit()
    print("YOU CAN CONTROL THE BIRD. 'U' FOR UP AND 'D' FOR DOWN.")
    SYCHOMMIE = input("DO YOU GO UP OR DOWN?")
    if SYCHOMMIE != 'U':
        print("THE BIRD CRASHES INTO A TREE. YOU FALL DOWN. THE END.")
        quit()
    print("YOU CAN CONTROL THE BIRD. 'U' FOR UP AND 'D' FOR DOWN.")
    SYCHOMMIE = input("DO YOU GO UP OR DOWN?")
    if SYCHOMMIE != 'D':
        print("THE BIRD CRASHES INTO A TREE. YOU FALL DOWN. THE END.")
        quit()
    print("YOU LAND SAFLEY AND SEE A CHEST.")
    time.sleep(1)
    print("YOU OPEN IT AND GET 20 COINS!")
    time.sleep(1)
    coins = 20
    print("YOU WIN! (ˆUˆ)")
    time.sleep(1)
    print("STATS:")
    time.sleep(1)
    print("YOU HAVE REACHED THE BEST POSSIBLE ENDING!!!")
    time.sleep(1)
    print("LEVEL", level)
    time.sleep(1)
    print("WEAPONS:")
    time.sleep(1)
    print(fav_weapon)
    time.sleep(1)
    print(fav_far_weapon)
    time.sleep(1)
    print("KEY ITEMS:")
    time.sleep(1)
    print(teleport_object)
    time.sleep(1)
    print("MONEY:")
    print(coins, "coins")
    print("USE THIS CODE IN THE RUNAWAY 3: a;sd|g($$")
    time.sleep(1)
    print("THE END.")
    quit()
if around != 'Stand':
    print("YOU GO AROUND THE LAKE AND HEAD TO THE VILLAGE.")
    time.sleep(1)
    print("YOU WIN!")
    time.sleep(1)
    print("STATS:")
    time.sleep(1)
    time.sleep(1)
    print("NOT BEST POSSIBLE ENDING")
    time.sleep(1)
    print("LEVEL", level)
    time.sleep(1)
    print("WEAPONS:")
    time.sleep(1)
    print(fav_weapon)
    time.sleep(1)
    print(fav_far_weapon)
    time.sleep(1)
    print("KEY ITEMS:")
    time.sleep(1)
    print(teleport_object)
    time.sleep(1)
    print("USE THIS CODE IN THE RUNAWAY 3: KSks(*98")
    time.sleep(1)
    print("THE END.")
    quit()
