
import time
age = eval(input("HOW OLD ARE YOU?"))
if age < 5:
    print("UH OH! YOU NEED TO BE 6 OR OLDER TO PLAY.")
    quit()
print("DO NOT SPAM ENTER.")
print("PLEASE ENTER OUT THIS FORM.")
fav_weapon = input("WHAT'S YOUR FAVORITE CLOSE-RANGED WEAPON? ")
fav_far_weapon = input("WHAT'S YOUR FAVORITE FAR-RANGED WEAPON? ")
teleport_object = input("WHAT'S YOUR FAVORITE FAST-TRAVEL ITEM? ")
print("[ROBOT]: BZZZT.")
time.sleep(1)
print("[ROBOT]: HI, WHAT IS YOUR NAME?")
time.sleep(1)
your_name = input("ENTER YOUR NAME: ")
print("[ROBOT]: HEY THERE", your_name, ".")
time.sleep(1)
print("[ROBOT]: MY NAME IS AADFOUTAMIE.")
time.sleep(1)
print("[AADFOUTAMIE]: WE ARE STUCK IN THE CAVE.")
time.sleep(1)
print("[AADFOUTAMIE]: WE GOT CAPTURED BY THE ZLASKOIY TRIBE. WE NEED TO GET OUT. CAN YOU HELP ME?")
time.sleep(1)
print("EITHER ENTER: Yes OR No")
yes_no = input("ENTER HERE: ")
if yes_no == 'No':
    print("[MONSTER]: GRRR...")
    time.sleep(1)
    print("[MONSTER]: RRAGH!")
    time.sleep(1)
    print("THE END.", your_name, "WAS SLAIN BY MONSTER.")
    quit()
print("[AADFOUTAMIE]: WATCH OUT!!!")
time.sleep(1)
print("A WOLF-LIKE MONSTER IS POUNCING AT YOU. DO YOU GO INTO THE PIT WITH THE ROBOT OR TO THE LEFT?")
time.sleep(1)
print("EITHER ENTER: Pit OR Left")
time.sleep(1)
oybadabam = input("ENTER HERE: ")
if oybadabam == 'Left':
    print("YOU RUN TO THE LEFT. YOU STOP. IT WAS A DEAD END!")
    time.sleep(1)
    print("[MONSTER]: GRRR...")
    time.sleep(1)
    print("[MONSTER]: RRAGH!")
    time.sleep(1)
    print("THE END.", your_name, "WAS SLAIN BY MONSTER.")
    quit()
print("YOU JUMP INTO THE PIT. YOUR PANTS START TO GET SOGGY. LUCKY YOU! YOU LANDED IN THE WATER!")
time.sleep(1)
print("THE MONSTER CAN'T SEE YOU IN THE PIT, SO HE GROANS AND WALKS AWAY.")
time.sleep(1)
print("[AADFOUTAMIE]: IT'S LUCKY THAT I'M WATERPROOF.")
time.sleep(1)
print("[AADFOUTAMIE]: SOMEHOW, I WASN'T BRAVE ENOUGH TO COME DOWN HERE ALL THOSE OTHER TIMES.")
time.sleep(1)
print("YOU LEVEL UP!!! 1 -> 2")
time.sleep(1)
input("PRESS ENTER TO CONTINUE")
level = 2
print("YOU SEE A CHEST.")
time.sleep(2)
print("THE ROBOT OPENS IT.")
time.sleep(1)
print("NOW YOU HAVE A", fav_weapon, "AND A", fav_far_weapon, "!!!")
input("PRESS ENTER TO CONTINUE")
print("[AADFOUTAMIE]: HEY, MY SENSOR CAN DETECT LIGHT IN THAT DIRECTION! FOLLOW ME!")
time.sleep(1)
print("YOU FOLLOW THE ROBOT.")
time.sleep(2)
print("YOU ARE OUT OF THE CAVE!!!")
time.sleep(1)
input("PRESS ENTER TO CONTINUE")
print("TO CONTINUE, PLEASE ENTER YOUR EMAIL.")
email = input("WHAT IS YOUR EMAIL? (THIS INFORMATION WILL NOT BE SHARED.) ")
print("PROCESSING PACKAGES...")
time.sleep(1)
print("LOADING 1 OF 3 PACKAGES...")
time.sleep(2)
print("LOADING 2 OF 3 PACKAGES...")
time.sleep(4)
print("LOADING 3 OF 3 PACKAGES...")
time.sleep(0.6)
input("PRESS ENTER TO CONTINUE")
print("_________  |________|   ________  ")
print("    |      |        |   |_______")
print("    |      |        |   |________")
print(" _________              __________    __________             __________       ")
print(" |_______|     |      | |        |    |________|  |       |  |________| |_______|")
print(" |        |    |______| |        |    |        |  |___|___|  |        |     |")
print("   _______")
print("      |")
print("      |")
print("   ___|___")
input("PRESS ENTER TO CONTINUE")
print("UH-OH! A GUARD CAUGHT YOU!")
time.sleep(1)
print("ARE YOU GOING TO FIGHT HIM?")
time.sleep(1)
buttohmussough = input("EITHER ENTER Yes OR No")
if buttohmussough != 'Yes':
    print("[GUARD]: HEIGH... YO AR NOTTE AE GUAARD!")
    time.sleep(1)
    print("YOU RUN AWAY.")
    time.sleep(1)
    print("[GUARD]: HEEEEEEIIGHHH YAAAAAAA!!!")
    time.sleep(1)
    print("THE GUARD HITS NOTHING.")
    time.sleep(1)
    print("YOU HAVE WON!")
    time.sleep(1)
    print("STATS:")
    time.sleep(1)
    print("NOT BEST POSSIBLE ENDING")
    time.sleep(1)
    print("LEVEL", level)
    time.sleep(1)
    print("WEAPONS:")
    time.sleep(1)
    print(fav_weapon)
    time.sleep(1)
    print("AND")
    time.sleep(1)
    print(fav_far_weapon)
    time.sleep(1)
    print("USE THIS CODE IN THE RUNAWAY 2: q1w2e3r4")
    time.sleep(1)
    print("THE END")
    quit()
print("BATTLE!!!")
time.sleep(1)
print("YOU ARE CLOSE TO THE GUARD. DO YOU USE CLOSE RANGE WEAPON OR FAR RANGED WEAPON?")
left = input("1 FOR CLOSE AND 2 FOR FAR. ")
if left != '1':
    print("UH-OH! FAR RANGED WEAPONS ARE WEAKER THAN CLOSE!")
    time.sleep(1)
    print("THE GUARD SMASHED YOU WITH HIS HAMMER.")
    time.sleep(1)
    print(your_name, "WAS SLAIN BY GUARD")
    quit()
print("[", your_name, "]: GRAHHGABAH!!!!!")
time.sleep(1)
print("...")
time.sleep(1)
input("PRESS ENTER TO SEE WHAT HAPPENED!")
print("YOU END UP SITTING ON THE GUARD.")
time.sleep(1)
print("[AADFOUTAMIE]: YEAH!!!")
time.sleep(1)
print("SOMEBODY APPEARS OUT OF NOWHERE.")
time.sleep(1)
print("[???]: WWWWHOO ARRREE YYYOOU???")
time.sleep(1)
boi = input("WHAT IS YOUR NAME?")
if boi != your_name:
    print("[???]:YYYOOUUU LLLIIIAARR...")
    time.sleep(1)
    print("[AADFOUTAMIE]: HUH??")
    time.sleep(1)
    print("YOU GET ZAPPED BY LIGHTNING.")
    time.sleep(1)
    print("[AADFOUTAMIE]: AHHHHHHH!!!")
    time.sleep(1)
    print(your_name, "WAS SLAIN BY ???")
    quit()
print("???'S HOOD VANISHED.")
time.sleep(1)
print("[???]: WELL, ASKING FOR YOUR NAME WAS A JOKE. *HEH!*")
time.sleep(1)
print("[???]: MY NAME IS PARADOX.")
time.sleep(1)
print("[PARADOX]: I READ YOUR MIND, SO YEAH.")
time.sleep(1)
print("YOU LEVEL UP!!! 2 -> 3")
time.sleep(1)
input("PRESS ENTER TO CONTINUE.")
level = 3
print("A HUGE WAVE OF WATER COMES.")
time.sleep(1)
print("[AADFOUTAMIE]: AAAAAHHHHH!!!")
time.sleep(1)
print("[PARADOX]: OH, THAT'S JUST MY SISTER.")
time.sleep(1)
print("[PARADOX'S SISTER]: HEYA! I'M OCTOPUS.")
time.sleep(1)
print("[AADFOUTAMIE]: WAIT. YOUR NAME IS OCTOPUS??")
time.sleep(1)
print("[OCTOPUS]: DON'T UNDERESTIMATE ME, ROBOT BOY. ")
time.sleep(1)
print("[OCTOPUS]: LAST I CHECKED, YOU WEREN'T THE ONE LAUGHING WHEN THAT WAVE CAME YOUR WAY.")
time.sleep(1)
print("[PARADOX]: YOU MIGHT NEED THIS CODE: LRLLRLL")
time.sleep(1)
print("PARADOX AND OCTOPUS VANISHES.")
time.sleep(1)
print("[AADFOUTAMIE]: HUMPH. WE DON'T NEED THEM.")
time.sleep(1)
print("[AADFOUMATIE]: AT LEAST 'PARADOX' GAVE US A CODE, BUT WE CAN'T USE IT YET.")
print("A CHEST APPEARS.")
time.sleep(1)
print("YOU OPEN IT.")
time.sleep(1)
print("THERE IS A", teleport_object, "INSIDE!!!")
time.sleep(1)
print("YOU EXIT THE VILLAGE. (ˆUˆ)")
time.sleep(1)
print("THE END")
time.sleep(1)
print("STATS:")
time.sleep(1)
print("YOU HAVE REACHED THE BEST POSSIBLE ENDING!!!")
time.sleep(1)
print("LEVEL", level)
time.sleep(1)
print("WEAPONS:")
time.sleep(1)
print(fav_weapon)
time.sleep(1)
print(fav_far_weapon)
time.sleep(1)
print("KEY ITEMS:")
time.sleep(1)
print(teleport_object)
time.sleep(1)
print("USE THIS CODE IN THE RUNAWAY 2: gGhH1!2@")
time.sleep(1)
print("THE END.")
quit()
print("BYE")
